language: python

sudo: required
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - build-essential
            - automake
            - git
            - libtool
            - python-dev
            - gettext
            - swig
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - build-essential
            - automake
            - git
            - libtool
            - python3.8-dev
            - gettext
            - swig
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && PYTHON=3.8"
      before_install:
        - pyenv global 3.8
        - pip3 install --upgrade pip tox six autopep8
      after_success:
        - ./build.sh
git:
  depth: 1

before_install:
  - pip install --upgrade pip tox six
  - eval "${MATRIX_EVAL}"

script:
- python -m compileall .

